baseURL = "https://carlosbuenosvinos.com"
languageCode = "en-us"
title = "Carlos Buenosvinos"
theme = "ananke"
googleAnalytics = "UA-42173983-1"

[params]
  favicon = ""
  description = "Carlos Buenosvinos | PHP, DevOps, Extreme Programming, Scrum and Domain-Driven Design"
  twitter = "https://twitter.com/buenosvinos"
  youtube = "http://www.youtube.com/user/carlosbuenosvinos"
  github = "https://github.com/carlosbuenosvinos"
  gitlab = ""
  linkedin = "http://es.linkedin.com/in/carlosbuenosvinos"
  show_reading_time = true
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/heroes/images/main-blog-hero.jpg"
  recent_posts_number = 20